### ISSUE TITLE
install plproxy in postgresql 9.6.1, encounter error

### ISSUE THREAD

**Issue by davidzwb** [plproxy/plproxy#24]
after make and make install in postgres 9.6.1's source code, whether I use 'create extention plproxy;' or 'psql -f ../../contrib/plproxy-2.6/sql/plproxy--2.6.0.sql', it all failed with the following error 'undefined symbol: heap_formtuple'.

**Comment by markokr** [comment]
Seems like plproxy was not compiled against 9.6 sources.

**Comment by Ormod** [comment]
Or since there's no 2.7 release of plproxy if the source files really are of the 2.6 release that one won't work with PG  9.6. In that case update to git master

**Comment by markokr** [comment]
Oh yes, seems it's instead a problem already fixed in master

**Comment by markokr** [comment]
There is now 2.7 out that fixed the issue.
