### ISSUE TITLE
Build error against PostgreSQL 11

### ISSUE THREAD

**Issue by devrimgunduz** [plproxy/plproxy#32]
Hi,

Getting this while building 2.8 against PostgreSQL 11. Can you please take a look? Thanks!

`gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include -DNO_SELECT=0 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/result.o src/result.c
src/parser.y:63.1-13: warning: deprecated directive, use '%name-prefix' [-Wdeprecated]
 %name-prefix="plproxy_yy"
 ^^^^^^^^^^^^^
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include -DNO_SELECT=0 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/type.o src/type.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include -DNO_SELECT=0 -I. -I./ -I/usr/pgsql-11/include/server -I/usr/pgsql-11/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/poll_compat.o src/poll_compat.c
src/function.c: In function 'fn_cache_delete':
src/function.c:204:14: warning: variable 'hentry' set but not used [-Wunused-but-set-variable]
  HashEntry  *hentry;
              ^~~~~~
src/function.c: In function 'fn_returns_dynamic_record':
src/function.c:217:7: error: too few arguments to function 'heap_attisnull'
   && (heap_attisnull(proc_tuple, Anum_pg_proc_proargmodes)
       ^~~~~~~~~~~~~~
In file included from src/plproxy.h:43,
                 from src/function.c:27:
/usr/pgsql-11/include/server/access/htup_details.h:805:13: note: declared here
 extern bool heap_attisnull(HeapTuple tup, int attnum, TupleDesc tupleDesc);
             ^~~~~~~~~~~~~~
src/function.c:218:10: error: too few arguments to function 'heap_attisnull'
       || heap_attisnull(proc_tuple, Anum_pg_proc_proargnames)))
          ^~~~~~~~~~~~~~
In file included from src/plproxy.h:43,
                 from src/function.c:27:
/usr/pgsql-11/include/server/access/htup_details.h:805:13: note: declared here
 extern bool heap_attisnull(HeapTuple tup, int attnum, TupleDesc tupleDesc);
             ^~~~~~~~~~~~~~
src/function.c: In function 'fn_get_return_type':
src/function.c:411:2: warning: enumeration value 'TYPEFUNC_COMPOSITE_DOMAIN' not handled in switch [-Wswitch]
  switch (rtc)
  ^~~~~~
src/function.c: In function 'fn_refresh_record':
src/function.c:439:16: warning: variable 'rtc' set but not used [-Wunused-but-set-variable]
  TypeFuncClass rtc;
                ^~~
make[1]: *** [<builtin>: src/function.o] Error 1
make[1]: *** Waiting for unfinished jobs....
src/cluster.c: In function 'reload_sqlmed_user':
src/cluster.c:591:29: error: 'ACL_KIND_FOREIGN_SERVER' undeclared (first use in this function); did you mean 'OBJECT_FOREIGN_SERVER'?
   aclcheck_error(aclresult, ACL_KIND_FOREIGN_SERVER, cluster->name);
                             ^~~~~~~~~~~~~~~~~~~~~~~
                             OBJECT_FOREIGN_SERVER
src/cluster.c:591:29: note: each undeclared identifier is reported only once for each function it appears in
src/cluster.c: In function 'reload_sqlmed_cluster':
src/cluster.c:660:29: error: 'ACL_KIND_FOREIGN_SERVER' undeclared (first use in this function); did you mean 'OBJECT_FOREIGN_SERVER'?
   aclcheck_error(aclresult, ACL_KIND_FOREIGN_SERVER, foreign_server->servername);
                             ^~~~~~~~~~~~~~~~~~~~~~~
                             OBJECT_FOREIGN_SERVER
make[1]: *** [<builtin>: src/cluster.o] Error 1
`

**Comment by ChristophBerg** [comment]
I got plproxy to build with the fixes from #31 and #33.

**Comment by markokr** [comment]
Fixed in master.
