### ISSUE TITLE
Is it possible to pass GUC settings to new connection that the launching process is using  ?

### ISSUE THREAD

**Issue by denishpatel** [plproxy/plproxy#39]
pg_background (https://github.com/vibhorkum/pg_background) extension allows to pass non-GIC session variables across the connection. See patch-4 from here https://postgrespro.com/list/thread-id/1848551
"Patch 4 adds infrastructure that allows one session to save all of its
non-default GUC values and another session to reload those values.
This was written by Amit Khandekar and Noah Misch.  It allows
pg_background to start up the background worker with the same GUC
settings that the launching process is using. "

Is it possible to achieve similar behavior in plproxy connection ?

**Comment by markokr** [comment]
pg_background works in in local cluster, and behaviour is specified as launching a new backend.

plproxy works against remote cluster, and behaviour is specified as query based, so per-connetion global settings are not proper unit to operate on.

So such feature would not fit plproxy world model. 

You could emulate it by adding extra arg to your functions embedding all settings there and then applying on remote side.

**Comment by denishpatel** [comment]
Makes sense. Thanks for quick response, @markokr !
