### ISSUE TITLE
cannot compile on MacOS Catalina & Posgres v12.3

### ISSUE THREAD

**Issue by ReLLL** [plproxy/plproxy#41]
When I try to compile plproxy on MacOS, I get the following error .  (after a fresh git clone)

$ make
/usr/bin/bison -b src/parser -d src/parser.y
**src/parser.y:61.9-18: syntax error, unexpected identifier, expecting string**
make: *** [src/parser.tab.c] Error 1

$ flex --version
flex 2.5.35 Apple(flex-32)
$ bison --version
bison (GNU Bison) 2.3

**Comment by markokr** [comment]
Please upgrade bison to 3.x.
