### ISSUE TITLE
Build error against PostgreSQL 13

### ISSUE THREAD

**Issue by devrimgunduz** [plproxy/plproxy#42]
Hi,

2.9 fails to build against PostgreSQL 13. 13.0 is out today. When will you push a new release that works against v13?

Regards, Devrim

src/function.c: In function 'plproxy_function_cache_init':
src/function.c:167:13: error: 'oid_hash' undeclared (first use in this function); did you mean 'uuid_hash'?
  167 |  ctl.hash = oid_hash;
      |             ^~~~~~~~
      |             uuid_hash
src/function.c:167:13: note: each undeclared identifier is reported only once for each function it appears in
make[1]: *** [<builtin>: src/function.o] Error 1
make[1]: *** Waiting for unfinished jobs....
src/execute.c: In function 'prepare_conn':
src/execute.c:288:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
  288 |    conn->cur->state = C_READY;
      |    ~~~~~~~~~~~~~~~~~^~~~~~~~~
src/execute.c:289:3: note: here
  289 |   case C_READY:
      |   ^~~~
src/execute.c:290:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
  290 |    if (check_old_conn(func, conn, &now))
      |       ^
src/execute.c:293:3: note: here
  293 |   case C_CONNECT_READ:
      |   ^~~~
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/plproxy/master/plproxy-2.9'
error: Bad exit status from /var/tmp/rpm-tmp.BOBXoo (%build)

**Comment by kmribti** [comment]
Solved by adding  **_#include <common/hashfn.h>_** in _**src/plproxy.h,**_ , at least it compile successfully.

**Comment by markokr** [comment]
Released 2.10, please check it out.

**Comment by devrimgunduz** [comment]
Thanks @markokr , pushed packages to the RPM repository.

Regards, Devrim
