### ISSUE TITLE
Add limit for run on all

### ISSUE THREAD

**Issue by noobtec** [plproxy/plproxy#45]
The `RUN ON ALL;` still sucks...

From the docs...

`Query will be run on all partitions in cluster in parallel.`

Can smb. please add a cfg limit so that it processes n partitions in parallel in blocks until it is done with all partitions?

**Comment by ZeeFiix** [comment]
Nice statement, but could you please describe why in detail it sucks ?
What's the problematic situation behind your statement and why you want to have it slowed down and processed in "batches" ?

**Comment by noobtec** [comment]
We solved the issue by not using plproxy anymore. Thanks anyway!

 
 

Gesendet: Donnerstag, 03. Juni 2021 um 07:02 Uhr
Von: "Robert Grumann" ***@***.***>
An: "plproxy/plproxy" ***@***.***>
Cc: "noobtec" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [plproxy/plproxy] Add limit for run on all (#45)


 

Nice statement, but could you please describe why in detail it sucks ?
What's the problematic situation behind your statement and why you want to have it slowed down and processed in "batches" ?

**Comment by markokr** [comment]
If you need to limit connections, one solution is to put pooler between plproxy and database.
