### ISSUE TITLE
Sort out NULL struct handling

### ISSUE THREAD

**Issue by df7cb** [plproxy/plproxy#46]
https://github.com/plproxy/plproxy/blob/b893edfda837171e307fcc0cb472ae1da1a6d5c6/test/expected/plproxy_test_2.out#L239-L242

This code chunk was introduced by 15a1438808 (by @markokr), and the net diff to plproxy_test.out is this:
```
$ diff -u plproxy_test.out plproxy_test_2.out 
--- plproxy_test.out	2018-05-29 11:56:22.669437487 +0200
+++ plproxy_test_2.out	2021-06-23 17:31:14.101479552 +0200
@@ -239,7 +239,7 @@
 select * from test_types2('types', NULL, NULL, NULL);
  v_posint | v_struct | arr 
 ----------+----------+-----
-          | (,)      | 
+          |          | 
 (1 row)
 
 -- test CONNECT
```

(The same diff is in plproxy_test_1.out (f1758d553 by me), but that one includes bogus "host=localhost" additions which result from a Debian-only patch.)

The `(,)` variant is present on PG9.6 and PG10 only.

Now libpq5 v14 is making this all worse since some error message used in these files is changing: (patch to be submitted)

```
$ diff -u plproxy_test.out plproxy_test_3.out 
--- plproxy_test.out	2021-09-13 10:59:04.854766806 +0200
+++ plproxy_test_3.out	2021-09-13 11:14:16.730226712 +0200
@@ -239,7 +239,7 @@
 select * from test_types2('types', NULL, NULL, NULL);
  v_posint | v_struct | arr 
 ----------+----------+-----
-          | (,)      | 
+          |          | 
 (1 row)
 
 -- test CONNECT
@@ -419,12 +419,12 @@
     cluster 'badcluster';
 $$ language plproxy;
 select * from test_bad_db();
-ERROR:  PL/Proxy function public.test_bad_db(0): [nonex_db] PQconnectPoll: FATAL:  database "nonex_db" does not exist
+ERROR:  PL/Proxy function public.test_bad_db(0): [nonex_db] PQconnectPoll: connection to server at "127.0.0.1", port 5432 failed: FATAL:  database "nonex_db" does not exist
 
 create function test_bad_db2() returns int4
 as $$
     connect 'dbname=wrong_name_db host=localhost';
 $$ language plproxy;
 select * from test_bad_db2();
-ERROR:  PL/Proxy function public.test_bad_db2(0): [wrong_name_db] PQconnectPoll: FATAL:  database "wrong_name_db" does not exist
+ERROR:  PL/Proxy function public.test_bad_db2(0): [wrong_name_db] PQconnectPoll: connection to server at "localhost" (::1), port 5432 failed: FATAL:  database "wrong_name_db" does not exist
 ```

Someone should decide which of the two output formats is correct, and patch plproxy to use it on all PG versions.
(Alternatively, we can wait until PG10 is out of support, but then we still have to remember to weed out the plproxy_test*.out files for the old versions. Until then, we have to maintain 2*2 files for all combinations.)

**Comment by markokr** [comment]
Fixed the libpq messages by dropping details in eda209b

Need to keep one alternative for struct case still.
