### ISSUE TITLE
PG16: plproxy.so: undefined symbol: pg_foreign_server_aclcheck

### ISSUE THREAD

**Issue by df7cb** [plproxy/plproxy#47]
plproxy needs some updates for PG16:

```
15:02:59 +ERROR:  could not load library "/<<PKGBUILDDIR>>/debian/postgresql-16-plproxy/usr/lib/postgresql/16/lib/plproxy.so": /<<PKGBUILDDIR>>/debian/postgresql-16-plproxy/usr/lib/postgresql/16/lib/plproxy.so: undefined symbol: pg_foreign_server_aclcheck
```

https://pgdgbuild.dus.dg-i.net/view/Binaries-Beta/job/postgresql-plproxy-binaries-beta/21/architecture=amd64,distribution=sid/console

**Comment by devrimgunduz** [comment]
Here is the build error against v16:

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -fvisibility=hidden -shared -o plproxy.so src/scanner.o src/parser.tab.o src/cluster.o src/execute.o src/function.o src/main.o src/query.o src/result.o src/type.o src/aatree.o -L/usr/pgsql-16/lib  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1   -L/usr/lib64  -L/usr/lib64 -Wl,--as-needed -Wl,-rpath,'/usr/pgsql-16/lib',--enable-new-dtags -fvisibility=hidden -L/usr/pgsql-16/lib -lpq 
src/cluster.c:651:14: error: call to undeclared function 'pg_foreign_server_aclcheck'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        aclresult = pg_foreign_server_aclcheck(um->serverid, um->userid, ACL_USAGE);
                    ^
src/cluster.c:722:14: error: call to undeclared function 'pg_foreign_server_aclcheck'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        aclresult = pg_foreign_server_aclcheck(foreign_server->serverid, info->user_oid, ACL_USAGE);
                    ^
2 errors generated.
make[1]: *** [/usr/pgsql-16/lib/pgxs/src/makefiles/../../src/Makefile.global:1080: src/cluster.bc] Error 1
make[1]: *** Waiting

**Comment by devrimgunduz** [comment]
@markokr can you please release a new tarball? I prefer a tarball to build the RPMs.

Regards, Devrim

**Comment by markokr** [comment]
Done

**Comment by df7cb** [comment]
Thanks!
