### ISSUE TITLE
Regression test failure with Postgres17beta3

### ISSUE THREAD

**Issue by M-Butter** [plproxy/plproxy#48]
Apparently there is an encoding problem with Postgres version 17beta3. See attached files.
[regression.diffs.txt](https://github.com/user-attachments/files/16559536/regression.diffs.txt)
[regression.out.txt](https://github.com/user-attachments/files/16559537/regression.out.txt)

The Postgres cluster was initialized as:
initdb -D data -E UTF8 --locale-provider=builtin --locale=C.UTF8 -k

**Comment by markokr** [comment]
This test tries out conversion between utf8<>non-utf8 encoding.  Unfortunately, non-utf8 databases can be created only in clusters created with LANG=C, but not with LANG=C.UTF8.  So this is expected failure.

**Comment by M-Butter** [comment]
Thanks for your reaction. And, sorry, I should have properly read the README.md as you already stated it there.

Regards,
Martin.
